version = 1
exclude_patterns = [
  "noxfile.py"
]
test_patterns = ["tests/**", "*_test.py", "tests/*.py"]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
